name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: derongan/nmsaction@v1
      with:
        rev: 1.15.1
    - name: Build with Maven
      run: mvn clean package
    - name: Test
      id: test
      run: |
        mkdir ~/work/NBTEditor/NBTEditor/testserver
        cd ~/.m2/repository/org/spigotmc/spigot
        find -type f -name '*-R0.1-SNAPSHOT.jar' -exec cp {} ~/work/NBTEditor/NBTEditor/testserver/server.jar \;
        cd ~/work/NBTEditor/NBTEditor/
        mkdir testserver/plugins
        cp target/NBTEditor-*-tests.jar testserver/plugins/
        cd testserver
        echo "eula=true" > eula.txt
        java -jar server.jar
        FILE=error.txt
        if [ -e "$FILE" ]; then
            ERROR='true'
        else
            ERROR='false'
        fi
    - name: Searching Error
      if: contains('${{ steps.test.outputs.ERROR }}', true)
      run: |
        echo Error Found!
        cd testserver
        cat error.txt
        exit 1