name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: derongan/nmsaction@v1
      with:
        rev: 1.16.1
    - name: Build with Maven
      run: mvn clean package
    - name: Running Tests
      id: test
      run: |
        mkdir ~/work/NBTEditor/NBTEditor/testserver
        cd nms-build/.m2/repository/org/spigotmc/spigot
        find -type f -name '*-R0.1-SNAPSHOT.jar' -exec cp {} ~/work/NBTEditor/NBTEditor/testserver/server.jar \;
        cd ~/work/NBTEditor/NBTEditor/
        mkdir testserver/plugins
        cp target/NBTEditor-*-tests.jar testserver/plugins/
        cd testserver
        echo "eula=true" > eula.txt
        echo stop | java -ea -jar server.jar
    - name: Searching for Failure
      run: |
        if [ -e "testserver/error.txt" ]; then
          echo "Error(s) Found:"
          cat testserver/error.txt
          exit 1
        fi